CustomerPortal/Controllers/BillPayController.cs
using CustomerPortal.Data;
using CustomerPortal.Models;
using CustomerPortal.Models.Enum;
using CustomerPortal.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace CustomerPortal.Controllers;

public class BillPayController : Controller
{
    private readonly MCBAContext _context;
    
    // Loads the CustomerID entered at Login
    private int CustomerID => HttpContext.Session.GetInt32(nameof(Customer.CustomerID)).Value;

    public BillPayController(MCBAContext context)
    {
        _context = context;
    }
    public async Task<IActionResult> CreateBill(int accountNumber)
    {

        var account = await FindAccount(accountNumber);
        
        if (account == null) { return RedirectToAction("Error","Home"); }
        
        var retDateTime = DateTime.Now;
        
        // Sets datetime to the current day and time and rounds the seconds to 0
        var dateTime = new DateTime(retDateTime.Year, retDateTime.Month,
            retDateTime.Day, retDateTime.Hour, retDateTime.Minute, 0);

        // gets list of all payees available
        var payees =  _context.Payee.ToList();
        
        // returns BillViewModel to View
        return View(
            new BillViewModel()
            {
                ScheduledTime = dateTime,
                AccountNumber = accountNumber,
                Balance = account.Balance,
                AccountType = account.AccountType,
                Payees = payees

            });
    }
    
    [HttpPost]
    public async Task<IActionResult> CreateBill(BillViewModel viewModel)
    {
        // Creates new BillPay to database using the data from BillViewModel
        _context.BillPay.Add(new BillPay()
        {
            Active = true,
            AccountNumber = viewModel.AccountNumber,
            ScheduleTimeUtc = viewModel.ScheduledTime.ToUniversalTime(),
            PayID = viewModel.BillPay.PayID,
            Amount = viewModel.BillPay.Amount,
            Period = viewModel.BillPay.Period
        });
        // Saves changes to Database
        await _context.SaveChangesAsync();
        return RedirectToAction("ViewBill", new{accountNumber = viewModel.AccountNumber});
    }
    
    public IActionResult ViewBill(int accountNumber)
    {
        
        HttpContext.Session.SetInt32(nameof(ViewBills),accountNumber);
        return RedirectToAction(nameof(ViewBills));
        
    }
    
    public async Task<IActionResult> ViewBills(int? page = 1)
    {
        var accountNumber = HttpContext.Session.GetInt32(nameof(ViewBills));

        var customer = await FindCustomer(CustomerID);
        
        ViewBag.Accounts = customer.Accounts.ToList();

        var account = await FindAccount(accountNumber.Value, CustomerID);

        if (account == null && accountNumber != 0)
        {
            return RedirectToAction("Index", "Customer");
        }
        
        ViewBag.Account = account;
        
        ViewBag.AccountNumber = accountNumber;

        // Page the orders, maximum of 5 per page.
        const int pageSize = 5;
        var pagedList = await _context.BillPay.Include(x=>x.Payee).Where(x => x.AccountNumber == accountNumber && !x.Failed).
            OrderBy(x => x.ScheduleTimeUtc).ToPagedListAsync(page, pageSize);
        
        return View(pagedList);
    }
    
    public async Task<IActionResult> CancelBill(int billID)
    {
        var bill = await FindBillPay(billID);

        if (bill != null)
        {
            _context.BillPay.Remove(bill);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ViewBills));
        }
        else
        {
            return RedirectToAction("Error","Home");
        }
       
        
    }
    
    // Method process the payment that the BillPay refers to.
    // Creates a new Transaction entry in the Database with 
    // the details from the billpay
    public async Task<IActionResult> PayBill(int billID)
    {
        
        var bill = await FindBillPay(billID);
        
        if (bill == null) { return RedirectToAction("Error", "Home");}
        
        var account = await FindAccount(bill.AccountNumber);

        if (account == null) { return RedirectToAction("Error", "Home");}

        decimal balance = account.Balance - bill.Amount;

        // Checks that the transaction payment will be valid for the accountType
        if ((account.AccountType == AccountType.Checking && balance < 300) ||
            (account.AccountType == AccountType.Saving && balance < 0))
        {
            // If the payment is invalid than the failed column in the object
            // is set to try and the bill entry in the database is updated
            bill.Failed = true;
            _context.BillPay.Update(bill);
        }
        else
        {
            bill.Failed = false;
        }
        // If bill is disabled than doesnt allow payment
        if (!bill.Active || bill.Failed)
        {
            return RedirectToAction(nameof(UnpaidBills));
        }
        else if (!bill.Active)
        {
            return RedirectToAction("Error","Home");
        }
        else
        {
            // New Transaction Created From BillPay data
            account.Balance -= bill.Amount;
            var transaction = new Transaction()
            {
                AccountNumber = bill.AccountNumber,
                Amount = bill.Amount,
                TransactionType = TransactionType.BillPay,
                TransactionTimeUtc = bill.ScheduleTimeUtc,
                Comment = $"{bill.Payee.Name}"
                
            };
            // If the billpay is montly than a new billpay is entered for the same
            // details but the date is set for the next month.
            if (bill.Period == PeriodType.Monthly)
            {
                await _context.BillPay.AddAsync(new BillPay()
                { 
                    AccountNumber = bill.AccountNumber,
                    Active = bill.Active,
                    Amount = bill.Amount,
                    PayID = bill.PayID,
                    ScheduleTimeUtc = bill.ScheduleTimeUtc.AddMonths(1),
                    Period = bill.Period,
                    Failed = false
                
                });
            }
            // Removes succesfully paid BillPay from database
            _context.BillPay.Remove(bill);
            await _context.Transaction.AddAsync(transaction);
        }
        
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(ViewBills));
        
    }

    // Method to begin the process of updating bill information and rif valid returns the 
    // user to the view that allows them to enter the new data.
    public async Task<IActionResult> EditBill(int billID)
    {
        
        var bill = await FindBillPay(billID);
        
        if (bill == null) { return RedirectToAction("Error", "Home");}

        var customer = await FindCustomer(CustomerID);

        bool valid = true;
        
        foreach (var account in customer.Accounts)
        {
            if (bill.AccountNumber == account.AccountNumber)
            {
                valid = true;
                break;
            }
            valid = false;
        }

        if (valid)
        {
            return View(
                new BillViewModel()
                {
                    BillPayID = billID,
                    ScheduledTime = bill.ScheduleTimeUtc.ToLocalTime(),
                    Amount = bill.Amount,
                    Accounts = customer.Accounts,
                    AccountNumber = bill.AccountNumber
                });
        }
        return RedirectToAction(nameof(ViewBills));
    }
    
    // Method for updating the bill information in the BillPay Table in database
    [HttpPost]
    public async Task<IActionResult> EditBill(BillViewModel viewModel)
    {
        
        var bill = await FindBillPay(viewModel.BillPayID);

        if (bill != null)
        {
            bill.Failed = false;
            bill.ScheduleTimeUtc = viewModel.ScheduledTime.ToUniversalTime();
            bill.Amount = viewModel.Amount;
            bill.AccountNumber = viewModel.AccountNumber;
        
            _context.BillPay.Update(bill);
            await _context.SaveChangesAsync();
        }
        
       
        return RedirectToAction(nameof(ViewBills));

    }
    
    public async Task<IActionResult> UnpaidBills(int? page = 1)
    {
        var accountNumber = HttpContext.Session.GetInt32(nameof(ViewBills));
        if (accountNumber == null)
        {
            return RedirectToAction("Error", "Home");
        }
        
        var account = await FindAccount(accountNumber.Value);
        
        ViewBag.Account = account;

        // Page the orders, maximum of 3 per page.
        const int pageSize = 5;
        
        var pagedList = await _context.BillPay.Include(x=>x.Payee).Where(x => x.AccountNumber == account.AccountNumber && x.Failed).
            OrderBy(x => x.ScheduleTimeUtc).ToPagedListAsync(page, pageSize);
       
        return View(pagedList);
    }

    public async Task<BillPay> FindBillPay(int billID)
    {
        return await _context.BillPay.FindAsync(billID);
    }
    public async Task<Account> FindAccount(int accountNumber)
    {
        return await _context.Account.Include(x => x.Transactions).Include(x => x.BillPay)
            .FirstOrDefaultAsync(x => x.AccountNumber == accountNumber);
    }
    public async Task<Account> FindAccount(int accountNumber,int customerID)
    {
        return await _context.Account.Include(x => x.Transactions).Include(x => x.BillPay)
            .FirstOrDefaultAsync(x => x.AccountNumber == accountNumber && x.CustomerID == customerID);
    }
    public async Task<Customer> FindCustomer(int customerID)
    {
        return await _context.Customer.Include(x => x.Accounts).Include(x=>x.Login)

CustomerPortal/Controllers/LoginController.cs
using CustomerPortal.Data;
using CustomerPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SimpleHashing.Net;

namespace A2Practice.Controllers;
[Route("/MCBA/Login")]
public class LoginController : Controller
{
    private static readonly ISimpleHash SimpleHash = new SimpleHash();
    private readonly MCBAContext _context;

    public LoginController(MCBAContext context) => _context = context;

    public IActionResult Index() => View();
    
    // Method For 
    [HttpPost]
    public async Task<IActionResult> Index(string loginID, string password)
    {
        var login = await _context.Login.Include(x=>x.Customer).
            FirstOrDefaultAsync(x=> x.LoginID == loginID);
        
        // Checks that all input fields are valid
        if (login == null || string.IsNullOrEmpty(password) || !SimpleHash.Verify(password, login.PasswordHash))
        {
            ModelState.AddModelError("LoginFailed","Login Failed. Please Try Again!");
            return View(new Login { LoginID = loginID });
        }

        // If Login Is diasbled by admin than an error message is disaplyed to user and they cannot 
        // proceed even with the correct details
        if (login.Disabled)
        {
            ModelState.AddModelError("LoginFailed","Your account is locked.");
            return View(new Login { LoginID = loginID });
        }
        
        // Login Customer
        HttpContext.Session.SetInt32(nameof(Customer.CustomerID),login.CustomerID);
        HttpContext.Session.SetString(nameof(Customer.Name),login.Customer.Name);

        return RedirectToAction("Index", "Customer");
        
    }

    // Method to return user to the landing page and 
    // clears all the data from the session
    [Route("Logout")]
    public IActionResult Logout()
    {
        // Clears the HTTP Session
        HttpContext.Session.Clear();
        return RedirectToAction("Index", "Home");
        
    }
    
}

CustomerPortal/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - A2Practice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="icon" type="image/png" href="/img/header.png"/>
</head>
<body>
    <header>
        <nav class="navbar shadow p-3 navbar-expand-sm navbar-light bg-light sticky-top">
            
               
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row ">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index" style="">
                        <img src="/img/Logo.png" class="img-fluid" alt="" style="width: 400px">
                    </a>
                    
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            var isLoggedIn = Context.Session.GetInt32(nameof(Customer.CustomerID)).HasValue;
                        }
                        @if (isLoggedIn)
                        {
                            <li class="nav-item" style="padding-left:5%;padding-right: 5%">
                                <a class="nav-link w3-text-black" asp-controller="Customer" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item" style="padding-right: 5%">
                                <a class="nav-link w3-text-black" asp-controller="Customer" asp-action="Profile">My Profile</a>
                            </li>
                            <li class="nav-item dropdown" style="padding-right: 5%">
                                <a class="nav-link dropdown-toggle w3-text-black" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Transactions
                                </a>
                                <ul class="dropdown-menu dropdown-menu-light w3-text-black" aria-labelledby="navbarDarkDropdownMenuLink">
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Deposit">Deposit</a></li>
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Withdraw">Withdraw</a></li>
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Transfer">Transfer</a></li>
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="IndexToViewStatements">Statements</a></li>
                                </ul>
                            </li>
                            <li class="nav-item" style="padding-right: 5%">
                                <a class="nav-link w3-text-black" asp-controller="BillPay" asp-action="ViewBill">Bills</a>
                            </li>
                        }
                    </ul>

                    <ul class="navbar-nav">

                        @if (isLoggedIn)
                        {
                            <li class="nav-item">
                                <span class="nav-link text-white" style="padding-right: 40px;">
                                    
                                @if(@Context.Session.GetString(nameof(Customer.DisplayPicture)).Equals("default"))
                                {
                                    <img src="/img/profile_image.png" height="40" width="40" alt=""/>
                                }
                                else
                                {
                                    <img src="data:image/png;base64,@Context.Session.GetString(nameof(Customer.DisplayPicture))" height="40" width="40" alt="">
                                }
                                   
                                </span>
                            </li>
                            <li class="nav-item">
                                <span class="nav-link w3-text-black" style="margin-right: 20px;width: max-content;padding-top: 15px">
                                    Welcome, @Context.Session.GetString(nameof(Customer.Name))
                                </span>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Login" asp-action="Logout">
                                   <button class="btn log-in-button btn-lg " style="width: 150px">
                                        <i class="fa fa-sign-out" style="padding-right: 30px"></i>Logout
                                    </button>
                                </a>
                            </li>
                        }
                        else
                        {
                            @if (ViewContext.RouteData.Values["controller"].ToString() != "Login" || ViewContext.RouteData.Values["action"].ToString() != "Blocked")
                            {
                                <a asp-controller="Login"asp-action="Index" style="text-align: center">
                                    <button class="btn log-in-button btn-lg " style="width: 150px">
                                        <i class="fa fa-sign-in " style="padding-right: 30px" ></i>Login
                                    </button>
                                </a>

                            }
                        }
                    </ul>

                </div>
        </nav>
    </header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>